name: genpoc
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc
  - trimmomatic
  - pigz
  - diamond
  - multiqc
  - unzip
  - bbmap
  - snakemake>=8.13.0
  - snakemake-storage-plugin-s3>=0.2.11
  - python>=3.12.0
  - pip:
      - arg-ranker==3.7.2
      