
# All rull defines all the output files that are needed to run the pipeline.  Each input should match a rules output below
rule all:
    input:
       "outputs/workflow_complete"      

include: "modules/step0-config.smk"

if any(str(step) in config["STEPS"] or "-" in step and int(step.split("-")[0]) <= int(s) <= int(step.split("-")[1]) for step in config["STEPS"].split(",") for s in ["1"]):
   include: "modules/step1-analyze.smk"

if any(str(step) in config["STEPS"] or "-" in step and int(step.split("-")[0]) <= int(s) <= int(step.split("-")[1]) for step in config["STEPS"].split(",") for s in ["2"]):
   include: "modules/step2-trim-merge.smk"

if any(str(step) in config["STEPS"] or "-" in step and int(step.split("-")[0]) <= int(s) <= int(step.split("-")[1]) for step in config["STEPS"].split(",") for s in ["3"]):
   include: "modules/step3-diamond.smk"

if any(str(step) in config["STEPS"] or "-" in step and int(step.split("-")[0]) <= int(s) <= int(step.split("-")[1]) for step in config["STEPS"].split(",") for s in ["4"]):
   include: "modules/step4-agr-ranker.smk"

if any(str(step) in config["STEPS"] or "-" in step and int(step.split("-")[0]) <= int(s) <= int(step.split("-")[1]) for step in config["STEPS"].split(",") for s in ["5"]):
   include: "modules/step5-antismash.smk"

include: "modules/step6-cleanup.smk"